# Change these first
owner: gigirassy # Your GitHub organization or username, where this repository lives
repo: blitzw-in-services-status # The name of this repository

sites:
  - name: Breezewiki [DK]
    url: https://fan.blitzw.in
  - name: Send [DK]
    url: https://send.blitzw.in
  - name: Stirling PDF [DK]
    url: https://pdf.blitzw.in
  - name: IT Tools [VERCEL]
    url: https://tools.blitzw.in
  - name: Privatebin (Bintz-wing) [DK]
    url: https://bin.blitzw.in
  - name: Mozhi [DK]
    url: https://moz.blitzw.in
  - name: LibreY [ZA]
    url: https://libre.blitzw.in
  - name: Wikimore [DK]
    url: https://wikimore.blitzw.in
  - name: SafeTwitch Frontend [DK]
    url: https://twitch.blitzw.in
  - name: SafeTwitch Backend [DK]
    url: https://twitchbackend.blitzw.in
  - name: Quetre [DK]
    url: https://q.blitzw.in
  - name: Tent [ZA]
    url: https://tent.blitzw.in
  - name: Structables [ZA]
    url: https://structables.blitzw.in
  - name: Intellectual [DK]
    url: https://genius.blitzw.in
  - name: Speedtest [DK]
    url: https://test.blitzw.in
  - name: ArchiveBox [DK]
    url: https://ab.blitzw.in

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.blitzw.in
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Blitzw.in Status
  introTitle: "Blitzw.in status."
  introMessage: "I should get an issue in my email if the site goes down and I'll work on it as soon as I can."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
